apiVersion: v1
kind: Service
metadata:
  name: node-app-service
spec:
  selector:
    app: node-app2 
  ports:
    - protocol: TCP
      port: 3000       
      targetPort: 3000 
  type: NodePort      
