name: ACR-image
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  generate-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Login to Azure Container Registry'
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          export IMAGE_VERSION=pr-${{ github.event.pull_request.number }}-stage
          IMAGE_TAG=${{ secrets.REGISTRY_LOGIN_SERVER }}/zwing-service:$IMAGE_VERSION
          docker build . -t $IMAGE_TAG
          docker push $IMAGE_TAG
          echo "IMAGE_VERSION=$IMAGE_VERSION" >> $GITHUB_ENV
    

      # - name: 'Build Docker image'
      #   run: |
      #     docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/zwing-service:${{ github.sha }}

      # - name: 'Push Docker image'
      #   run: |
      #     docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/zwing-service:${{ github.sha }}


