name: image-creation-pipeline
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  generate-image:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository code
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Log in to DockerHub
      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # Step 3: Build the Docker image
      - name: Build the image
        run: |
          docker build -t action-test-2dec:latest .

      # Step 4: Tag and push the Docker image to DockerHub
      - name: Push Docker Image
        run: |
          docker tag action-test-2dec:latest ${{ secrets.DOCKER_USERNAME }}/action-test-2dec:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/action-test-2dec:latest
