name: Docker Image CI/CD
env:
  REGISTRY: action-test2de
on:
  push:
    branches:
      - main # Runs the workflow when changes are pushed to the 'main' branch
  workflow_dispatch: # Allows manual triggering of the workflow
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v4
      
      # Step 2: Set up Docker Buildx for advanced build features
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      # Step 3: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      # Step 4: Build and Push Docker Image
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        run: |
          # Check if Dockerfile exists
          if [ ! -f Dockerfile ]; then
            echo "Error: Dockerfile not found"
            exit 1
          fi
          
          # Build the Docker image
          docker build \
            -t ${{ secrets.DOCKER_USERNAME }}/${{env.REGISTRY}}:latest \
            -t ${{ secrets.DOCKER_USERNAME }}/${{env.REGISTRY}}:${{ github.sha }} \
            .
          
          # Push the images
          docker push ${{ secrets.DOCKER_USERNAME }}/${{env.REGISTRY}}:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/${{env.REGISTRY}}:${{ github.sha }}
        
        # Add error handling
        continue-on-error: false
      
      # Optional: Scan image for vulnerabilities
      - name: Scan Docker image
        uses: anchore/scan-action@v3
        with:
          image: ${{ secrets.DOCKER_USERNAME }}/${{env.REGISTRY}}:latest
          fail-build: false
          severity-cutoff: critical







