name: image-creation-pipeline
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  generate-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build the Docker Image
        run: |
          docker build -t action-test-2dec:latest .

      - name: Push Docker Image
        run: |
          docker tag action-test-2dec:latest ${{ secrets.DOCKER_USERNAME }}/action-test-2dec:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/action-test-2dec:latest
